In [ ]:
## Representing tokens as vectors such that semantic meaning is captured (similar meaning words have similar vectors)
## Done via training


In [2]:
## Pretrained token embeddings like Word2vec, Glove
## LLMs dont use pretrained embeddings, but rather learn the token embeddings as part of their training along with learning the model weights

In [ ]:
## Embedding layer weight Matrix of shape vocab size x embedding dimension (d) where every token ID is mapped to a vector of dimension d
## The embedding layer weight matrix is initialized randomly and then optimized with backprop in training


In [ ]:
import torch

input_ids = torch.tensor([2, 3, 5, 1]) ## Token IDs as input
print(input_ids)

tensor([2, 3, 5, 1])


In [6]:
## Sample vocab size and d
vocab_size = 6
output_dim = 3

torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim) # Random initialization of the embedding matri

print(embedding_layer)
print(embedding_layer.weight)

Embedding(6, 3)
Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [ ]:
## Lookup
print(embedding_layer(torch.tensor([3]))) ## Vector for token ID 3

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)


In [ ]:
print(embedding_layer(input_ids)) ## Embeddings for our sequence of token IDs of shape seq length x d

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)
